#pragma once

#define ENGINE_KEY_W 87
#define ENGINE_KEY_A 65
#define ENGINE_KEY_S 83
#define ENGINE_KEY_D 68
#define ENGINE_KEY_UP 265
#define ENGINE_KEY_DOWN 264
#define ENGINE_KEY_LEFT 263
#define ENGINE_KEY_RIGHT 262
#define ENGINE_KEY_ENTER 257